require("config")
require("action")
status={}

function status.getCurStatus(candidateStatus)
	keepScreen(true)
	for k,v in pairs(candidateStatus) do
		local x,y=findColor(v.point)
	end
	keepScreen(false)
end

status.common={
	startFight={
		name="startFight",
		point=nil,
		nextStatus={"gear"},
		execTime=60
	},
	gear={
		name="gear",
		point=nil,
		nextStatus={"tangle","victoryRGB","noRevive"},
		execTime=300
	},
	tangle={
		name="tangle",
		point=nil,
		nextStatus={"victoryRGB","noRevive"},
		execTime=300
	},
	victoryRGB={
		name="victoryRGB",
		point=nil,
		nextStatus={"victory"},
		execTime=20
	},
	victory={
		name="victory",
		point=nil,
		nextStatus={"saleRune","confirmReward"},
		execTime=20
	},
	confirmReward={
		name="confirmReward",
		point=nil,
		nextStatus={"again"},
		execTime=20
	},
	saleRune={
		name="saleRune",
		point=nil,
		nextStatus={"again","confirmSaleRune"},
		execTime=20
	},
	confirmSaleRune={
		name="confirmSaleRune",
		point=nil,
		nextStatus={"again"},
		execTime=20
	},
	again={
		name="again",
		point=nil,
		nextStatus={"gear","openStore"},
		execTime=60
	},
	noRevive={
		name="noRevive",
		point=nil,
		nextStatus={"defeat"},
		execTime=20
	},
	defeat={
		name="defeat",
		point=nil,
		nextStatus={"prepareBattle"},
		execTime=100
	},
	prepareBattle={
		name="prepareBattle",
		point=nil,
		nextStatus={"startFight"},
		execTime=20
	},
	openStore={
		name="openStore",
		point=nil,
		nextStatus={"clickEnerge"},
		execTime=20
	},
	clickEnerge={
		name="clickEnerge",
		point=nil,
		nextStatus={"buyEnerge"},
		execTime=20
	},
	buyEnerge={
		name="buyEnerge",
		point=nil,
		nextStatus={"finishBuyConfirm"},
		execTime=20
	},
	
	finishBuyConfirm={
		name="finishBuyConfirm",
		point=nil,
		nextStatus={"closeStore"},
		execTime=20
	},
	
	closeStore={
		name="closeStore",
		point=nil,
		nextStatus={"again"},
		execTime=20
	},
	
	startList={"startFight","gear"}
--		startList={"again"}
}



--带狗粮
status[0]={
	startFight=status.common.startFight,
	gear=status.common.gear,
	tangle=status.common.tangle,
	victoryRGB=status.common.victoryRGB,
	victory=status.common.victory,
	confirmReward=status.common.confirmReward,
	saleRune=status.common.saleRune,
	confirmSaleRune=status.common.confirmSaleRune,
	
	again=status.common.again,
	noRevive=status.common.noRevive,
	defeat=status.common.defeat,
	prepareBattle=status.common.prepareBattle,
	
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore=status.common.closeStore,
	
	startList=status.common.startList
}

--觉醒
status[1]={
	startFight=status.common.startFight,
	gear=status.common.gear,
	tangle=status.common.tangle,
	victoryRGB=status.common.victoryRGB,
	victory={
		name="victory",
		point=nil,
		nextStatus={"confirmReward"},
		execTime=20
	},
	confirmReward=status.common.confirmReward,
	
	again=status.common.again,
	noRevive=status.common.noRevive,
	defeat=status.common.defeat,
	prepareBattle=status.common.prepareBattle,
	
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore=status.common.closeStore,
	
	startList=status.common.startList
}

--符文
status[2]={
	startFight=status.common.startFight,
	gear={
		name="gear",
		point=nil,
		nextStatus={"tangle","littleBoss","victoryRGB","noRevive"},
		execTime=100
	},
	tangle={
		name="tangle",
		point=nil,
		nextStatus={"littleBoss","victoryRGB","noRevive"},
		execTime=100
	},
	littleBoss={
		name="littleBoss",
		point=nil,
		nextStatus={"bigBoss","victoryRGB","noRevive"},
		execTime=300
	},
	bigBoss={
		name="bigBoss",
		point=nil,
		nextStatus={"victoryRGB","noRevive"},
		execTime=300
	},
	victoryRGB=status.common.victoryRGB,
	victory={
		name="victory",
		point=nil,
		nextStatus={"keepRune","confirmReward"},
		execTime=20
	},
	confirmReward=status.common.confirmReward,
	keepRune={
		name="keepRune",
		point=nil,
		nextStatus={"again"},
		execTime=20
	},
	again=status.common.again,
	noRevive=status.common.noRevive,
	defeat=status.common.defeat,
	prepareBattle=status.common.prepareBattle,
	
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore=status.common.closeStore,
	
	startList=status.common.startList
}

--塔
status[3]={
	startFight={
		name="startFight",
		point=nil,
		nextStatus={"gear","openStore"},
		execTime=60
	},
	gear={
		name="gear",
		point=nil,
		nextStatus={"tangle","littleBoss","victoryRGB","defeat"},
		execTime=300
	},
	tangle={
		name="tangle",
		point=nil,
		nextStatus={"littleBoss","victoryRGB","defeat"},
		execTime=300
	},
	littleBoss={
		name="littleBoss",
		point=nil,
		nextStatus={"victoryRGB","defeat"},
		execTime=300
	},
	victoryRGB=status.common.victoryRGB,
	victory={
		name="victory",
		point=nil,
		nextStatus={"confirmReward"},
		execTime=20
	},
	confirmReward={
		name="confirmReward",
		point=nil,
		nextStatus={"nextStage"},
		execTime=20
	},
	nextStage={
		name="nextStage",
		point=nil,
		nextStatus={"startFight"},
		execTime=20
	},
	defeat=status.common.defeat,
	--prepareBattle=status.common.prepareBattle,
	
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore={
		name="closeStore",
		point=nil,
		nextStatus={"startFight"},
		execTime=20
	},
	
	startList=status.common.startList
}

--三星碎片
status[4]={
	startFight=status.common.startFight,
	gear={
		name="gear",
		point=nil,
		nextStatus={"tangle","littleBoss","rbTalk"},
		execTime=300
	},
	tangle={
		name="tangle",
		point=nil,
		nextStatus={"littleBoss","rbTalk"},
		execTime=300
	},
	littleBoss={
		name="littleBoss",
		point=nil,
		nextStatus={"rbTalk"},
		execTime=300
	},
	rbTalk={
		name="rbTalk",
		point=nil,
		nextStatus={"confirmReward"},
		execTime=20
	},
	confirmReward=status.common.confirmReward,
	again=status.common.again,
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore=status.common.closeStore,
	
	startList=status.common.startList
}

--异界队长
status[5]={
	owStartFight={
		name="owStartFight",
		point=nil,
		nextStatus={"owConfirmStartFight"},
		execTime=300
	},
	owConfirmStartFight={
		name="owConfirmStartFight",
		point=nil,
		nextStatus={"owGear"},
		execTime=120
	},
	owGear={
		name="owGear",
		point=nil,
		nextStatus={"owVictory","owDefeat"},
		execTime=300
	},
	owVictory={
		name="owVictory",
		point=nil,
		nextStatus={"confirmReward","keepRune"},
		execTime=20
	},
	confirmReward={
		name="confirmReward",
		point=nil,
		nextStatus={"owSameTeamAgain"},
		execTime=20
	},
	keepRune={
		name="keepRune",
		point=nil,
		nextStatus={"owSameTeamAgain"},
		execTime=20
	},
	owDefeat={
		name="owDefeat",
		point=nil,
		nextStatus={"owSameTeamAgain"},
		execTime=20
	},
	owSameTeamAgain={
		name="owSameTeamAgain",
		point=nil,
		nextStatus={"owStartFight","openStore"},
		execTime=100
	},
	
	openStore=status.common.openStore,
	clickEnerge=status.common.clickEnerge,
	buyEnerge=status.common.buyEnerge,
	finishBuyConfirm=status.common.finishBuyConfirm,
	closeStore={
		name="closeStore",
		point=nil,
		nextStatus={"owSameTeamAgain"},
		execTime=20
	},
	
	startList={"owStartFight","owGear"}
}

--异界队员
status[6]={
	owReadyToFight={
		name="owReadyToFight",
		point=nil,
		nextStatus={"owGear"},
		execTime=60
	},
	owGear=status[5].owGear,
	owVictory=status[5].owVictory,
	confirmReward=status[5].confirmReward,
	keepRune=status[5].keepRune,
	owDefeat=status[5].owDefeat,
	owSameTeamAgain={
		name="owSameTeamAgain",
		point=nil,
		nextStatus={"owReadyToFight"},
		execTime=100
	},
	openStore=status[5].openStore,
	clickEnerge=status[5].clickEnerge,
	buyEnerge=status[5].buyEnerge,
	finishBuyConfirm=status[5].finishBuyConfirm,
	closeStore=status[5].closeStore,
	
	startList={"owReadyToFight","owGear"}
}
--合成精髓
status[7]={
	synthesis={
		name="synthesis",
		point=nil,
		nextStatus={"confirmSynthesis","synthesisOk"},
		execTime=20
	},
	confirmSynthesis={
		name="confirmSynthesis",
		point=nil,
		nextStatus={"synthesis","synthesisOk"},
		execTime=20
	},
	synthesisOk={
		name="synthesisOk",
		point=nil,
		nextStatus={"synthesis","confirmSynthesis"},
		execTime=20
	},
	startList={"synthesis","confirmSynthesis","synthesisOk"}
}
--竞技场
status[8]={
	victory={
		name="victory",
		point=nil,
		nextStatus={"tangle","pureDefeat"},
		execTime=150
	},
	tangle={
		name="tangle",
		point=nil,
		nextStatus={"victory","pureDefeat"},
		execTime=150
	},
	pureDefeat={
		name="pureDefeat",
		point=nil,
		nextStatus={"tangle","victory"},
		execTime=150
	},
	startList={"tangle","victory","pureDefeat"}
}


function status.init()
	action.init()
	--初始化point
	for k,v in pairs(status[config.battleType]) do
		v.point=config.points[k]
		v.action=action[k]
		--添加自己到next
		if v.nextStatus~=nil then
			v.nextStatus[#v.nextStatus+1]=v.name
		end
	end
end

return status